import {inter, bion} from './fonts';
import "@/app/styles/global.scss";
import type { Metadata } from "next";
import Header from './components/core/header/Header';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const className = `${inter.variable} ${bion.variable}`;

  return (
    <html lang="en" className={className}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
